diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: "left_joint"
  right_wheel: "right_joint"
  publish_rate: 50
  cmd_vel_timeout: 0.5
  base_frame_id: "base_link"
  wheel_separation: 0.3
  wheel_radius: 0.05

